# Generated by Django 6.0.1 on 2026-01-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='currency',
            field=models.CharField(blank=True, choices=[('rub', 'RUB'), ('usd', 'USD'), ('eur', 'EUR')], default='rub', max_length=3, null=True),
        ),
    ]
