# Generated by Django 6.0.1 on 2026-01-08 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
