# Generated by Django 6.0.1 on 2026-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('currency', models.CharField(choices=[('rub', 'RUB'), ('usd', 'USD'), ('eur', 'EUR')], default='rub', max_length=3, verbose_name='Валюта')),
            ],
        ),
    ]
